#pragma once
// countries.hpp - ISO 3166-1 alpha-2 country codes and names for Reflector
#include <string>
#include <vector>
#include "../../popups.hpp"

inline std::vector<ListOption> get_all_countries() {
    return {
        {"Worldwide", "Worldwide", false},
        {"AF", "Afghanistan", false},
        {"AL", "Albania", false},
        {"DZ", "Algeria", false},
        {"AS", "American Samoa", false},
        {"AD", "Andorra", false},
        {"AO", "Angola", false},
        {"AI", "Anguilla", false},
        {"AQ", "Antarctica", false},
        {"AG", "Antigua and Barbuda", false},
        {"AR", "Argentina", false},
        {"AM", "Armenia", false},
        {"AW", "Aruba", false},
        {"AU", "Australia", false},
        {"AT", "Austria", false},
        {"AZ", "Azerbaijan", false},
        {"BS", "Bahamas", false},
        {"BH", "Bahrain", false},
        {"BD", "Bangladesh", false},
        {"BB", "Barbados", false},
        {"BY", "Belarus", false},
        {"BE", "Belgium", false},
        {"BZ", "Belize", false},
        {"BJ", "Benin", false},
        {"BM", "Bermuda", false},
        {"BT", "Bhutan", false},
        {"BO", "Bolivia", false},
        {"BA", "Bosnia and Herzegovina", false},
        {"BW", "Botswana", false},
        {"BR", "Brazil", false},
        {"IO", "British Indian Ocean Territory", false},
        {"BN", "Brunei Darussalam", false},
        {"BG", "Bulgaria", false},
        {"BF", "Burkina Faso", false},
        {"BI", "Burundi", false},
        {"CV", "Cabo Verde", false},
        {"KH", "Cambodia", false},
        {"CM", "Cameroon", false},
        {"CA", "Canada", false},
        {"KY", "Cayman Islands", false},
        {"CF", "Central African Republic", false},
        {"TD", "Chad", false},
        {"CL", "Chile", false},
        {"CN", "China", false},
        {"CX", "Christmas Island", false},
        {"CC", "Cocos (Keeling) Islands", false},
        {"CO", "Colombia", false},
        {"KM", "Comoros", false},
        {"CD", "Congo, Democratic Republic of the", false},
        {"CG", "Congo", false},
        {"CK", "Cook Islands", false},
        {"CR", "Costa Rica", false},
        {"HR", "Croatia", false},
        {"CU", "Cuba", false},
        {"CW", "Curaçao", false},
        {"CY", "Cyprus", false},
        {"CZ", "Czechia", false},
        {"CI", "Côte d'Ivoire", false},
        {"DK", "Denmark", false},
        {"DJ", "Djibouti", false},
        {"DM", "Dominica", false},
        {"DO", "Dominican Republic", false},
        {"EC", "Ecuador", false},
        {"EG", "Egypt", false},
        {"SV", "El Salvador", false},
        {"GQ", "Equatorial Guinea", false},
        {"ER", "Eritrea", false},
        {"EE", "Estonia", false},
        {"SZ", "Eswatini", false},
        {"ET", "Ethiopia", false},
        {"FK", "Falkland Islands (Malvinas)", false},
        {"FO", "Faroe Islands", false},
        {"FJ", "Fiji", false},
        {"FI", "Finland", false},
        {"FR", "France", false},
        {"GF", "French Guiana", false},
        {"PF", "French Polynesia", false},
        {"TF", "French Southern Territories", false},
        {"GA", "Gabon", false},
        {"GM", "Gambia", false},
        {"GE", "Georgia", false},
        {"DE", "Germany", false},
        {"GH", "Ghana", false},
        {"GI", "Gibraltar", false},
        {"GR", "Greece", false},
        {"GL", "Greenland", false},
        {"GD", "Grenada", false},
        {"GP", "Guadeloupe", false},
        {"GU", "Guam", false},
        {"GT", "Guatemala", false},
        {"GG", "Guernsey", false},
        {"GN", "Guinea", false},
        {"GW", "Guinea-Bissau", false},
        {"GY", "Guyana", false},
        {"HT", "Haiti", false},
        {"HM", "Heard Island and McDonald Islands", false},
        {"VA", "Holy See", false},
        {"HN", "Honduras", false},
        {"HK", "Hong Kong", false},
        {"HU", "Hungary", false},
        {"IS", "Iceland", false},
        {"IN", "India", false},
        {"ID", "Indonesia", false},
        {"IR", "Iran, Islamic Republic of", false},
        {"IQ", "Iraq", false},
        {"IE", "Ireland", false},
        {"IM", "Isle of Man", false},
        {"IL", "Israel", false},
        {"IT", "Italy", false},
        {"JM", "Jamaica", false},
        {"JP", "Japan", false},
        {"JE", "Jersey", false},
        {"JO", "Jordan", false},
        {"KZ", "Kazakhstan", false},
        {"KE", "Kenya", false},
        {"KI", "Kiribati", false},
        {"KP", "Korea, Democratic People's Republic of", false},
        {"KR", "Korea, Republic of", false},
        {"KW", "Kuwait", false},
        {"KG", "Kyrgyzstan", false},
        {"LA", "Lao People's Democratic Republic", false},
        {"LV", "Latvia", false},
        {"LB", "Lebanon", false},
        {"LS", "Lesotho", false},
        {"LR", "Liberia", false},
        {"LY", "Libya", false},
        {"LI", "Liechtenstein", false},
        {"LT", "Lithuania", false},
        {"LU", "Luxembourg", false},
        {"MO", "Macao", false},
        {"MG", "Madagascar", false},
        {"MW", "Malawi", false},
        {"MY", "Malaysia", false},
        {"MV", "Maldives", false},
        {"ML", "Mali", false},
        {"MT", "Malta", false},
        {"MH", "Marshall Islands", false},
        {"MQ", "Martinique", false},
        {"MR", "Mauritania", false},
        {"MU", "Mauritius", false},
        {"YT", "Mayotte", false},
        {"MX", "Mexico", false},
        {"FM", "Micronesia, Federated States of", false},
        {"MD", "Moldova, Republic of", false},
        {"MC", "Monaco", false},
        {"MN", "Mongolia", false},
        {"ME", "Montenegro", false},
        {"MS", "Montserrat", false},
        {"MA", "Morocco", false},
        {"MZ", "Mozambique", false},
        {"MM", "Myanmar", false},
        {"NA", "Namibia", false},
        {"NR", "Nauru", false},
        {"NP", "Nepal", false},
        {"NL", "Netherlands", false},
        {"NC", "New Caledonia", false},
        {"NZ", "New Zealand", false},
        {"NI", "Nicaragua", false},
        {"NE", "Niger", false},
        {"NG", "Nigeria", false},
        {"NU", "Niue", false},
        {"NF", "Norfolk Island", false},
        {"MK", "North Macedonia", false},
        {"MP", "Northern Mariana Islands", false},
        {"NO", "Norway", false},
        {"OM", "Oman", false},
        {"PK", "Pakistan", false},
        {"PW", "Palau", false},
        {"PS", "Palestine, State of", false},
        {"PA", "Panama", false},
        {"PG", "Papua New Guinea", false},
        {"PY", "Paraguay", false},
        {"PE", "Peru", false},
        {"PH", "Philippines", false},
        {"PN", "Pitcairn", false},
        {"PL", "Poland", false},
        {"PT", "Portugal", false},
        {"PR", "Puerto Rico", false},
        {"QA", "Qatar", false},
        {"RO", "Romania", false},
        {"RU", "Russian Federation", false},
        {"RW", "Rwanda", false},
        {"RE", "Réunion", false},
        {"BL", "Saint Barthélemy", false},
        {"SH", "Saint Helena, Ascension and Tristan da Cunha", false},
        {"KN", "Saint Kitts and Nevis", false},
        {"LC", "Saint Lucia", false},
        {"MF", "Saint Martin (French part)", false},
        {"PM", "Saint Pierre and Miquelon", false},
        {"VC", "Saint Vincent and the Grenadines", false},
        {"WS", "Samoa", false},
        {"SM", "San Marino", false},
        {"ST", "Sao Tome and Principe", false},
        {"SA", "Saudi Arabia", false},
        {"SN", "Senegal", false},
        {"RS", "Serbia", false},
        {"SC", "Seychelles", false},
        {"SL", "Sierra Leone", false},
        {"SG", "Singapore", false},
        {"SX", "Sint Maarten (Dutch part)", false},
        {"SK", "Slovakia", false},
        {"SI", "Slovenia", false},
        {"SB", "Solomon Islands", false},
        {"SO", "Somalia", false},
        {"ZA", "South Africa", false},
        {"GS", "South Georgia and the South Sandwich Islands", false},
        {"SS", "South Sudan", false},
        {"ES", "Spain", false},
        {"LK", "Sri Lanka", false},
        {"SD", "Sudan", false},
        {"SR", "Suriname", false},
        {"SJ", "Svalbard and Jan Mayen", false},
        {"SE", "Sweden", false},
        {"CH", "Switzerland", false},
        {"SY", "Syrian Arab Republic", false},
        {"TW", "Taiwan", false},
        {"TJ", "Tajikistan", false},
        {"TZ", "Tanzania, United Republic of", false},
        {"TH", "Thailand", false},
        {"TL", "Timor-Leste", false},
        {"TG", "Togo", false},
        {"TK", "Tokelau", false},
        {"TO", "Tonga", false},
        {"TT", "Trinidad and Tobago", false},
        {"TN", "Tunisia", false},
        {"TR", "Turkey", false},
        {"TM", "Turkmenistan", false},
        {"TC", "Turks and Caicos Islands", false},
        {"TV", "Tuvalu", false},
        {"UG", "Uganda", false},
        {"UA", "Ukraine", false},
        {"AE", "United Arab Emirates", false},
        {"GB", "United Kingdom", false},
        {"US", "United States", false},
        {"UY", "Uruguay", false},
        {"UZ", "Uzbekistan", false},
        {"VU", "Vanuatu", false},
        {"VE", "Venezuela", false},
        {"VN", "Viet Nam", false},
        {"WF", "Wallis and Futuna", false},
        {"EH", "Western Sahara", false},
        {"YE", "Yemen", false},
        {"ZM", "Zambia", false},
        {"ZW", "Zimbabwe", false}
    };
}
