#!/bin/bash
# build.sh - Build script for HarukaInstaller
# Run from the project root directory.
# Usage:
#   ./build.sh           - Show usage
#   ./build.sh test-ui   - Build the TUI test (with simulated data)
#   ./build.sh cmake     - Build with CMake
#   ./build.sh clean     - Clean build artifacts

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALLER_DIR="$SCRIPT_DIR/installer"

CXX="${CXX:-g++}"
CXXFLAGS="-std=c++17 -Wall -Wextra -I$INSTALLER_DIR/lib/ncurses"
LDFLAGS="-lncursesw"

SRCDIR="$INSTALLER_DIR/lib/ncurses"
OUTDIR="$SCRIPT_DIR/build"

# ── Parse VERSION file ───────────────────────────────────────────────────────
VERSION_FILE="$SCRIPT_DIR/VERSION"
if [ -f "$VERSION_FILE" ]; then
    # Source it to get variables (they use bash-compatible key="value" format)
    eval "$(grep '^installer=' "$VERSION_FILE")"
    eval "$(grep '^license=' "$VERSION_FILE")"
    eval "$(grep '^author=' "$VERSION_FILE")"
    VERSION_ID="${installer:-dev}"
    VERSION_LICENSE="${license:-MIT}"
    VERSION_AUTHOR="${author:-unknown}"
else
    VERSION_ID="dev"
    VERSION_LICENSE="MIT"
    VERSION_AUTHOR="unknown"
fi

# Generate version header from VERSION file
VERSION_GEN="$INSTALLER_DIR/lib/ncurses/versioning/version_gen.hpp"
cat > "$VERSION_GEN" <<VEOF
// Auto-generated by build.sh — do not edit
#pragma once
#define VERSION_ID "$VERSION_ID"
#define VERSION_LICENSE "$VERSION_LICENSE"
#define VERSION_AUTHOR "$VERSION_AUTHOR"
VEOF

echo "HarukaInstaller v$VERSION_ID (License: $VERSION_LICENSE, Author: $VERSION_AUTHOR)"
echo ""

mkdir -p "$OUTDIR"

case "${1:-}" in
    test-ui)
        echo "==> Building TUI test..."
        $CXX $CXXFLAGS -DTESTUI \
            "$SRCDIR/ncurseslib.cpp" \
            "$SRCDIR/mainmenu/mainmenu.cpp" \
            "$SRCDIR/test/testing.cpp" \
            $LDFLAGS \
            -o "$OUTDIR/test_ui"
        echo "==> Built: $OUTDIR/test_ui"
        echo "    Run with: $OUTDIR/test_ui"
        ;;

    clean)
        echo "==> Cleaning build artifacts..."
        rm -rf "$OUTDIR"
        rm -rf "$SCRIPT_DIR/cmake-build"
        echo "==> Done."
        ;;

    cmake)
        echo "==> Building with CMake..."
        mkdir -p "$SCRIPT_DIR/cmake-build" && cd "$SCRIPT_DIR/cmake-build"
        cmake -DBUILD_TEST_UI=ON ..
        cmake --build .
        echo "==> Built: cmake-build/test_ui"
        ;;

    *)
        echo "Usage: ./build.sh [test-ui|cmake|clean]"
        echo ""
        echo "  test-ui   Build the ncurses TUI test program"
        echo "  cmake     Build using CMake"
        echo "  clean     Remove all build artifacts"
        ;;
esac
