// Versioning
// Version info is generated by build.sh into version_gen.hpp
// Or passed via cmake compile definitions.
// Fallback defaults provided if neither is available.
#pragma once

#include <string>

// Try to include auto-generated version header
#if __has_include("version_gen.hpp")
#include "version_gen.hpp"
#endif

#ifndef VERSION_ID
#define VERSION_ID "dev"
#endif

#ifndef VERSION_LICENSE
#define VERSION_LICENSE "MIT"
#endif

#ifndef VERSION_AUTHOR
#define VERSION_AUTHOR "Mizumo-prjkt"
#endif

namespace Versioning {
    inline const char* version()  { return VERSION_ID; }
    inline const char* license()  { return VERSION_LICENSE; }
    inline const char* author()   { return VERSION_AUTHOR; }

    inline std::string full_title() {
        return std::string("HarukaInstall v") + VERSION_ID;
    }
}
